# Generated by Django 2.2.2 on 2019-06-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('profile_app', '0002_permission_subuserprofile'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdata',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='menu.Menu'),
        ),
        migrations.AddField(
            model_name='billdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_data', to='profile_app.MainUserProfile'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='profile_app.MainUserProfile'),
        ),
    ]
