# Generated by Django 2.2.2 on 2019-07-01 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20190629_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdata',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billdata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
