# Generated by Django 2.2.2 on 2019-06-28 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=55)),
                ('birthday', models.DateField()),
                ('_added', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_blocked', models.BooleanField(default=False)),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user_profile', to='profile_app.MainUserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_see', models.BooleanField(default=False)),
                ('inventory_add', models.BooleanField(default=False)),
                ('inventory_mod', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user_permission', to='profile_app.SubUserProfile')),
            ],
        ),
    ]
