# Generated by Django 2.2.2 on 2019-06-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190629_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryfoodin',
            old_name='price_per',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='inventoryotherin',
            old_name='price_per',
            new_name='price',
        ),
    ]
