# Generated by Django 2.2.2 on 2019-07-01 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190629_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryfoodin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryfoodout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryotherin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryotherout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
